### ISSUE TITLE
Listingblock height is wrong

### ISSUE THREAD

**Issue by batjko** [Ruffianjiang/hexo-theme-pure#5]
Hi there,

I have just installed your theme and somehow the code blocks in the hell9o-world page are stretched out extremely.

![image](https://user-images.githubusercontent.com/7287076/102015189-f2cb7f00-3d51-11eb-81ea-864439db2152.png)

It turns out that the block is wrapped in a `listingblock` class, which appears to add this height and I don't know why.

Can you help?

**Comment by Ruffianjiang** [comment]
Do you mean that all articles are on the front page?
I tried to fix them, and now they're working.

Thank you very much for your attention.

Reference links for fixes are as follows:
https://hexo.io/zh-cn/docs/variables
https://hexo.io/zh-cn/docs/helpers#paginator

**Comment by batjko** [comment]
I meant just the fact that there is this huge gap between list items, apparently by default.
As you can see, there is this giant ~1000 pixel gap between one list item and the next one. (The page shown is the default hello world one in every Hexo starter project).

**Comment by Ruffianjiang** [comment]
Sorry! I has no idea.
I tried use plugins `highlight` and `prismjs`, they all seem to be working correctly as follows. and I can not find `div[class='listingblock ']`.
![image](https://user-images.githubusercontent.com/16110477/102636967-498cea80-4190-11eb-873b-9fa05c1cf1af.png)

![image](https://user-images.githubusercontent.com/16110477/102637353-d46de500-4190-11eb-9739-c874507366c7.png)

Can you provide  Syntax Highlighting plugin you used?
If you use the default config, i think you can run the following command in the hexo root directory. 
`hexo clean & hexo generate & hexo serve`
